---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  selector: # A StatefulSet uses the match labels pattern as Deployments
    matchLabels:
      app: mariadb-sts
  # serviceName This is a link to the headless service which is defined at the bottom of the file
  serviceName: mariadb-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb-sts
    spec:
      # StatefulSet requires that a graceful termination period be set. This is the number
      # of seconds that the Pod has to exit on its own before being terminated.
      terminationGracePeriodSeconds: 10
      containers:
        - name: mariadb-container
          image: mariadb:latest
          volumeMounts:
            # The volume claim matching this name is defined in the volumeClaimTemplates section
            - name: mariadb-pvc
              mountPath: /var/lib/mysql
          resources:
            requests:
              cpu: 1
              memory: 4Gi
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: 'your database password'
  # Unique to Statefulset, we can define a template of a PersisantVolumeClaim just like we define the
  # template of the pod replicas. This template is used to create the PersistentVolumeClaims, associating
  # one to each of the pod replicas.
  volumeClaimTemplates:
    - metadata:
        name: mariadb-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
---
# The headless services for this StatefulSet (required)
# NOTE: the headless service  means that unlike every other Service we created so far there is no service
# endpoint with load balancing. The service has no IP, external or internal. It exists so that the pods in
# the StatefulSet can get their own network identities so that they can be addressed. Remember that each pod
# in the stateful set is unique (unlike with Deployments), and is given an incrementing integer value known as
# the ordinal, so it’s common to address them individually and directly. This is opposed to Pods in a
# Deployment where each pod is given a random id. If a Pod in a Stateful set is recreated (like when moved
# from one node to another during an update) it will retain the same identifying ordinal, whereas Pods that
# are replaced in a Deployment are assigned a new random name.
#
# Pods can be addressed at STATEFULSET_NAME-POD_ORDINAL.SERVICE_NAME
# In this example, our single pod can be referenced using the DNS address: mariadb-
# 0.mariadb-service. From outside the namespace, you can append the namespace e.g.:
# mariadb-0-mariadb-service.production.svc
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  ports:
    - port: 3306
  clusterIP: None
  selector:
    app: mariadb-sts
