name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      # fixing this shape of syntax, (because it causing script injection)
      # - name: Assign label
      #   run: |
      #     issue_title="${{ github.event.issue.title }}"
      #     if [[ "$issue_title" == *"bug"* ]]; then
      #     echo "Issue is about a bug!"
      #     else
      #     echo "Issue is not about a bug"
      #     fi
      - name: Assign label
        env:
          TITLE: ${{ github.event.issue.title }}
        # So if you are using user generated values like the title of an issue, it's strongly recommended
        # that you first store them in an environment variable, before using those values anywhere in the commands
        # you are executing.
        run: |
          if [[ "$TITLE" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
