---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  #  Set this to be the identity of your developer. For GKE, this is a Google User who has
  #  “Kubernetes Engine Cluster Viewer” IAM role access to the project
  name: developerA
  namespace: team1
roleRef:
  kind: Role
  name: developer-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Google Cloud user account
  - kind: User
    name: example@gmail.com
#
#
# Note that the acceptable values within the User subject are governed by your Kubernetes
# platform, and any identity systems you have configured. With Google Cloud, the name here
# can be any Google user. RBAC authorizes the user to the actions specified in the Role, however
# in order to authenticate the user, they need the clusters.get permission which is configured
# outside of Kubernetes (the “Kubernetes Engine Cluster Viewer” role allows users to
# authenticate to the cluster, without granting any further permission, after which RBAC can be
# used). The exact steps here will vary depending on your platform provider.
#
#
