---
# To use a secret mounted as a volume, the pod manifest should declare the
# volume and it should be mounted in the container’s spec:
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
    - name: container-with-secret
      image: g1g1/py-kube:0.3
      command: ['/bin/bash', '-c', 'while true ; do sleep 10 ; done']
      volumeMounts:
        # binds the pod volume to the mount in the container. Multiple containers can mount the same volume.
        # When this pod is running, the username and password are available as files under /etc/hush-hus
        - name: secret-volume
          mountPath: '/mnt/hush-hush'
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: hush-hush
