#!/usr/bin/env ansible-playbook
# Let’s say you want to check that you can connect to a remote server
# on a particular port. If you can’t, you want Ansible to treat that
# as an error and stop running the play.
---
- name: Can reach server
  hosts: all

  tasks:
    - name: Run my shell script
      script: scripts/can_reach.sh www.google.com 80 1
      tags:
        - script
        - shell

    - name: Run my perl script
      environment:
        LANGUAGE: en_US.UTF-8
        LC_ALL: en_US.UTF-8
      script: scripts/can_reach.pl www.google.com 80
      tags:
        - script
        - perl

    - name: Run my custom module
      can_reash:
        host: localhost
        port: 22
        timeout: 1
      tags:
        - module

    - name: Run my custom module again (failing)
      can_reash:
        host: example.com
        port: 5432
      tags: module
