---
# Volume clones are new volumes that are populated with the content of an existing volume.
# Once the volume cloning is complete there is no relation between the original and the
# clone. Their content will diverge over time
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-of-pvc-1
  namespace: myns

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cloning
  resources:
    requests:
      storage: 5Gi
    dataSource:
      kind: PersistentVolumeClaim
      name: pvc-1
