---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test

spec:
  volumeSnapshotClassName: csi-hostpath-snapclass
  source:
    persistentVolumeClaimName: pvc-test

#
#
---
# You can also provision volumes from a snapshot.
# Here is a persistent volume claim bound to a snapshot:
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-pvc

spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: new-snapshot-test
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io

  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
