---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv

spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: { EBS volume ID }

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - { availability zone }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: some-pod

spec:
  containers:
    - image: some-container
      name: some-container
      volumeMounts:
        - name: persistent-storage
      mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
      claimName: ebs-claim
