---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: music
    service: music
  name: hue-music
spec:
  containers:
    - name: hue-music
      image: busybox
      livenessProbe:
        httpGet:
          path: /pulse
          port: 8888
          httpHeaders:
            - name: X-Custom-Header
              value: ItsAlive
        initialDelaySeconds: 30
        timeoutSeconds: 1

        # readinessProbe:
        #   exec:
        #     command:
        #       - /usr/local/bin/checker
        #       - --full-check
        #       - --data-service=hue-multimedia-service
        #   initialDelaySeconds: 60
        #   timeoutSeconds: 5

        # ports:
        #   - name: liveness-port
        #     containerPort: 8080
        #     hostPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: liveness-port
        #   failureThreshold: 1
        #   periodSeconds: 10
        # startupProbe:
        #   httpGet:
        #     path: /healthz
        #     port: liveness-port
        #   failureThreshold: 30
        #   periodSeconds: 10
