# restrict the resource usage of a given namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name:
    demo-resourcequota # can be anything you like. The namespaces it affects depends on
    # which namespaces you apply the manifest to
spec:
  hard:
    pods: '100' # sets a hard limit of 100 Pods running at once in that namespace
