---
# autoscaling for the hue-reminders Deployment, apply it or intead:
# k autoscale deployment hue-reminders --min=10 --max=15 --cpu-percent=90
# then perform a rolling update from version 2.2 to 3.0:
#  k set image deployment/hue-reminders hue-reminders=g1g1/hue-reminders:3.0 # ⬇️⬇️⬇️⬇️⬇️
#
# Waiting for deployment "hue-reminders" rollout to finish: 1 old replicas are pending termination...
# Waiting for deployment "hue-reminders" rollout to finish: 1 old replicas are pending termination...
# Waiting for deployment "hue-reminders" rollout to finish: 1 old replicas are pending termination...
# Waiting for deployment "hue-reminders" rollout to finish: 8 of 10 updated replicas are available...
# Waiting for deployment "hue-reminders" rollout to finish: 9 of 10 updated replicas are available...
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hue-reminders
spec:
  maxReplicas: 15
  minReplicas: 10
  targetCPUUtilizationPercentage: 90
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hue-reminders
