---
# uses first:
# apply from  ch9/redis-statefulset.yaml
# kubectl create -f deploy_worker.yaml
# kubectl exec -it deploy/pi-worker -- python3 add_tasks.py
# $ kubectl logs -f deployment/pi-worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pi-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: pi
  template:
    metadata:
      labels:
        pod: pi
    spec:
      containers:
        - name: pi-container
          image: docker.io/wdenniss/pi_worker:1
          env:
            - name: REDIS_HOST
              value: redis-0.redis-service
            - name: PYTHONUNBUFFERED
              value: '1'
