---
apiVersion: v1
kind: Secret
metadata:
  name: secrets-production
# type: Opaque means that from kubernetes's point of view the contents of
# this Secret is unstructured, it can contain arbitrary key-value pairs.

# In contrast, there is the Secret storing ServiceAccount credentials,
# or the ones used as ImagePullSecret. These have a constrained contents.
type: Opaque
stringData:
  SECRET_KEY: secret_value
  ANOTHER_KEY: another_value
data:
  ENCODED_KEY: VGhpcyBzdHJpbmcKbWlnaHQgYmUgaGFyZCB0byByZXByZXNlbnQgaW4gWUFNTCDwn5iFCg==
#
#
# $ echo "secret_value" | base64
#   c2VjcmV0X3ZhbHVlCg==
# $ echo "c2VjcmV0X3ZhbHVlCg==" | base64 -D
#   secret_value
#
#
