---
- name: deploy httpd container
  hosts: all
  become: true
  gather_facts: false
  vars:
    webroot: '/webroot'
  tasks:
    - name: podman installed
      ansible.builtin.yum:
        name: podman
        state: latest

    - name: pull image
      containers.podman.podman_image:
        name: httpd
        pull: true
        tag: latest

    # Note that because of modern Red Hat systems come with SELinux enabled, so you need
    # to set the container_share_t SELinux Context; otherwise, the files aren’t
    # shared between the host and the guest.
    - name: webroot present
      ansible.builtin.file:
        path: '{{ webroot }}'
        state: directory
        owner: 'root'
        group: 'root'
        mode: '0777'
        setype: 'container_share_t'

    - name: custom index.html
      ansible.builtin.copy:
        dest: '{{ webroot }}/index.html'
        content: |
          Custom Web Page
        setype: 'container_share_t'

    # $ ansible-galaxy collection install containers.podman
    - name: run httpd container
      containers.podman.podman_container:
        name: webserver
        image: httpd
        state: started
        detach: true
        expose:
          - 80
        ports:
          - 8080:80
        volume:
          - '{{ webroot }}:/usr/local/apache2/htdocs/:exec'
