---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  # bind 0.0.0.0 means bind to all interfaces so that other Pods can connect
  # appendonly: yes means enable the append log to persist data to disk
  # NOTE: The important thing is that we’re persisting the Redis state to the
  # /redis/data directory, so it can be reloaded if the Pod is re-created
  redis.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode no
    appendonly yes
    dir /redis/data
