---
#
# The NodePortservice type is similar to a ClusterIP service, but it also opens a port on each
# node. Opening a port allows access to the service from inside the cluster (using the ClusterIP).
# External users can connect directly to the node on the NodePort. A random port is opened on the
# local node for each service unless the nodeport property specifies a specific port. The kube-proxy
# container forwards traffic from the port to the service’s cluster IP and then to the pod
# that’s updating the IPtable rules.
#
apiVersion: v1
kind: Service
metadata:
  name: 'nginx-example'
  namespace: 'mynamespace'
spec:
  type: NodePort
  selector:
    app: 'nginx'
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
      nodeport: 25000
