---
- name: Show any variable during debugging.
  hosts: all
  gather_facts: true
  tasks:
    - debug: var="{{ variable }}"
# $ ansible-playbook 5-15-variable-variable.yml -e variable=ansible_python
